#!/usr/bin/python

##################

onclick = 'i3-msg workspace 99:; exec xournal'
onhold  = 'temp=`mktemp`; scrot -e "mv \$f $temp"; convert "$temp" "$temp.pdf"; ' + onclick + ' "$temp.pdf"'

##################

import subprocess
import re

click = r"> 02 8(0 20 0F 00 0B 00 04 00 1B 1D|1 20 0F 00 0B 00 04 00 1B 19) 00 08 00 6F 00 00 00 00 00"
hold  = r"> 02 80 20 0F 00 0B 00 04 00 1B 1D 00 08 00 6D 00 00 00 00 00"

proc = subprocess.Popen("hcidump att -R".split(), stdout=subprocess.PIPE)

while True:
    pkt = proc.stdout.readline().strip().decode("utf-8")
    #print(pkt)
    if re.match(click, pkt):
        print("click")
        subprocess.call(onclick.split())
    elif re.match(hold, pkt):
        print("hold")
        subprocess.call(onhold, shell=True)
